apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: default
type: Opaque
data:
  MONGO_USERNAME: cm9vdA==   # base64 encoded username 'root'
  MONGO_PASSWORD: MjAwMw==   # base64 encoded password '2003'
  jwt-public-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS1NSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVExcE1JSUJDb0tDQVFQQTRUY0o2ekFKNU94WWxpOXdKdWFEbEdHSktjeGxwNWRHVU1SYUpJVmRsT0kya3lVTVQ0SS81amh0WndRYVBVZUFnUmtXbDFsdE1ldzk4S3NVSHhHeFhiUEk3aFRGZWZZVGhlNFgwZVJLbllhc1JWTTRFM0x1cEs1UlQwd3kvTHBjQ2RudGpqcmtscEJRY05zd25MbW5uN1gyclV3YWZyNTE3anBLOFMzVG5nL2cyZEZBbElUeEZGZ0pnUWo1YlRTdzcxcFl0a01qQ0ZPTTg5YmFoZUU2bFZsZWhOMlFZdlg1OGlMMzkwbExWQmlva0tzWWkwM0xxakEzNUtrUzFGOTdkbmZuMEFTTU9UQmVZbmVyTjJYYWVOVHlscmVMcEhzZCsyMXUwdklHZUNMK2ZuMHBJLzRIQlBENGYxTkpMQjFtVXdFYzBsRDBWcG9tQ0srOUY1WkVXUU13SURBUUFC



#echo -n 'your_value' | base64
