# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: MjAwMw==   # base64 encoded "2003"
  mysql-user: cm9vdA==            # base64 encoded "root"
  mysql-password: cGFzc3dvcmQ=    # base64 encoded "password"
